config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts do
    resources :contents

  end
  resources :posts do
    resources :comments
  end

  namespace :admin do
    resources :users
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope { order('created_at ASC')}

  belongs_to :post
  belongs_to :user

  validates :text, :presence => true
end

app/models/content.rb
class Content < ActiveRecord::Base
  default_scope { order('created_at ASC')}

  belongs_to :post
  belongs_to :user


  validates :entry, :presence => true


end

app/models/post.rb
class Post < ActiveRecord::Base
    default_scope { order('created_at DESC')}

  belongs_to :user
  has_many :contents, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts, dependent: :destroy
         has_many :contents, dependent: :destroy
         has_many :comments, dependent: :destroy
end

app/controllers/admin/users.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action do
    unless current_user && current_user.admin?
      redirect_to posts_path, alert: 'You are not admin'
    end
  end
  before_action :find_user, except: [:new, :create, :index]

  def index
    @users = User.all
  end

  def edit

  end
  def create
    @user = User.create( user_params )
  end


  def show
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:admin, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, except: [:new, :create, :index]

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)

    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:post_id])
    if @comment.update(comment_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :author, :post_id, :user_id)
  end
end

app/controllers/contents.controller.rb
class ContentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @content = @post.contents.new
  end

  def show
    @post = Post.find(params[:post_id])
    @content = Content.find(params[:id])
    render :show
  end

  def create
    @post = Post.find(params[:post_id])
    @content = @post.contents.new(content_params)
    if @content.save
      redirect_to post_path(@content.post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @content = @post.contents.find(params[:id])
    render :edit
  end

  def update
    @content = Content.find(params[:post])
    if @content.update(content_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    redirect_to posts_path
  end
end

private
def content_params
  params.require(:content).permit(:name)
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @content = @post.contents.new
  end

  def show
    @post = Post.find(params[:post_id])
    @content = Content.find(params[:id])
    render :show
  end

  def create
    @post = Post.find(params[:post_id])
    @content = @post.contents.new(content_params)
    if @content.save
      redirect_to post_path(@content.post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @content = @post.contents.find(params[:id])
    render :edit
  end

  def update
    @content = Content.find(params[:post_id])
    if @content.update(content_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    redirect_to posts_path
  end
end

private
def content_params
  params.require(:content).permit(:entry)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:new, :create, :index]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
    render :index
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to  posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:name)
  end

  def find_post
  @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment] do |f| %>
<%= f.label :comment %>:
<%= f.text_field :text %>
<p><%= f.submit %></p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form" %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render "form" %>

app/views/contents/_form.html.erb
<%= render('layouts/errors', :object => @content) %>

<%= form_for [@post, @content] do |f| %>
<%= f.label :entry %>
<%= f.text_area :entry %>
<p><%= f.submit %></p>

<% end %>

app/views/contents/edit.html.erb
<h1>Edit Post Content</h1>

<%= render "form" %>

app/views/contents/new.html.erb
<h1><%= @post.name %></h1>

<%= render 'form' %>

<li><%= link_to "Return to Posts", posts_path %></li>

app/views/contents/show.html.erb
<h1><%=  @content.entry %></h1>
<hr>
<br>
<p><%= link_to "Return to Post", post_path(@post) %><p>

<!-- Checkout the tabbing of your if/end and your each loops. -->

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>You broke it, dummy!</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <b><%= link_to "The official blog of Brandon Seroyer", posts_path, id:'flickr', class: "navbar-brand" %></b>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <!-- <ul class="nav navbar-nav">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
      </ul>
    </li>
  </ul> -->
  <ul class="nav navbar-nav navbar-right">

    <% unless current_user %>
    <li><%= link_to 'Sign in', new_user_session_path, id:'text-color', class: "navbar-brand"  %></li>
    <li><%= link_to 'Sign up', new_user_registration_path, id:'text-color', class: "navbar-brand"  %></li>
    <% else %>
    <li><%= link_to 'New Post', new_post_path, id:'text-color', class: "navbar-brand" %></li>
    <li><%= link_to current_user.email, edit_user_registration_path, id:'text-color', class: "navbar-brand"  %></li>
    <li><%= link_to 'Log out',  destroy_user_session_path, method: 'delete', id:'text-color', class: "navbar-brand"  %></li>
    <% end %>
</p>



  </ul>
</div><!--/.nav-collapse -->
</div>
</nav>

<div class='container'>
  <% if alert %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>

  <% if notice %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>
  <br>

  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post </i><%= @post.name%></i></h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h3>Posts</h3>
<ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.name, post_path(post) %></li>
<% end %>
</ul>

<hr>

<%= link_to "Add New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

<hr>

<%= link_to "back to Index", posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.name %></h1>

<% if @post.contents.any? %>
<ul>
  <% @post.contents.each do |content| %>

    <%= content.entry %> |
    <%= link_to "Edit", edit_post_content_path(@post, content) %> |
    <%= link_to "Delete", post_content_path(@post, content),
    :data => {:confirm => "Are you sure?",
      :method => "delete"} %>

    <% end %>
  </ul>
  <% else %>
  <p> There is no content yet!</p>
  <% end %>
  <p><%= link_to "Add New Content", new_post_content_path(@post) %></p>

  <hr>
    <% if @post.comments.any? %>
    <ul>
      <% @comments.each do |comment| %>
      <li>
        <%= comment.text %>
        <% if current_user.id == @post.user_id %>
        <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
        <%= link_to "Delete", post_comment_path(@post, comment),
        :data => {:confirm => "Are you sure?",
          :method => "delete"} %>
          <% end %>

        </li>
        <% end %>
      </ul>
      <% else %>
      <p>There are no comments yet!</p>
      <% end %>

      <p><%= link_to "Add an comment", new_post_comment_path(@post) %></p>
<hr>
<ul>
  <li><%= link_to "Edit Post", edit_post_path %></li>
  <li><%= link_to "Return to Posts", posts_path %></li>
  <li><%= link_to "Add a new Post", new_post_path %></li>
  <li><%= link_to "Delete Post", post_path(@post),
  :data => {:confirm => "Are you sure?",
    :method => "delete"} %></li>
</ul>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>